// monorepo/native/desktop/maplefile-cli/internal/domain/collectiondto/interface.go
package collectiondto

import (
	"context"

	"go.mongodb.org/mongo-driver/bson/primitive"

	"github.com/mapleapps-ca/monorepo/native/desktop/maplefile-cli/internal/domain/user"
)

type CreateCollectionRequestDTO struct {
	// --- Authentication
	UserData *user.User

	// --- Payload
	Collection *CollectionDTO
}

type GetCollectionRequestDTO struct {
	// --- Authentication
	UserData *user.User

	// --- Payload
	ID primitive.ObjectID
}

// CollectionDTORepository defines the interface for interacting with the cloud service
// to manage CollectionDTOs. These DTOs represent encrypted collection data
// exchanged between the local device and the cloud server.
type CollectionDTORepository interface {
	// CreateInCloud creates a new CollectionDTO on the cloud service.
	// A new ID will be generated by the service, assigned to the provided `collection`
	// object, and returned.
	// It returns the ID of the created CollectionDTO and an error if the operation fails.
	CreateInCloud(ctx context.Context, req *CreateCollectionRequestDTO) (*primitive.ObjectID, error)

	// GetFromCloudByID fetches a CollectionDTO by its unique identifier from the cloud service.
	// It returns the CollectionDTO if found, or an error if not found or another issue occurs.
	// A specific error (e.g., domain.ErrNotFound) should be returned if the ID does not exist.
	GetFromCloudByID(ctx context.Context, req *GetCollectionRequestDTO) (*CollectionDTO, error)

	// ListFromCloud lists CollectionDTOs from the cloud service based on the provided filter criteria.
	// An empty filter should return all accessible CollectionDTOs.
	// It returns a slice of matching CollectionDTOs or an error if the listing fails.
	// The returned slice is guaranteed to be non-nil, even if no collections match the filter (it will be an empty slice).
	ListFromCloud(ctx context.Context, filter CollectionFilter) ([]*CollectionDTO, error)

	// DeleteInCloudByID deletes a CollectionDTO by its unique identifier from the cloud service.
	// It returns an error if the deletion fails, for example, if the ID does not exist
	// or due to permissions issues. A specific error (e.g., domain.ErrNotFound)
	// should be returned if the ID does not exist.
	DeleteInCloudByID(ctx context.Context, id primitive.ObjectID) error
}

// CollectionFilter defines filtering options for listing CollectionDTOs.
// Fields are optional; an empty filter implies no filtering.
type CollectionFilter struct {
	// ParentID filters collections that are children of the specified ParentID.
	// If nil, collections are not filtered by parent.
	ParentID *primitive.ObjectID `json:"parent_id,omitempty"`
	// Type filters collections by their 'Type' field.
	// If empty, collections are not filtered by type.
	Type string `json:"type,omitempty"`
}
