// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/security/password/password.go
//
// Generated by this command:
//
//	mockgen -source=pkg/security/password/password.go -destination=pkg/mocks/mock_security_password.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	securestring "github.com/mapleapps-ca/monorepo/cloud/mapleapps-backend/pkg/security/securestring"
	gomock "go.uber.org/mock/gomock"
)

// MockPasswordProvider is a mock of PasswordProvider interface.
type MockPasswordProvider struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordProviderMockRecorder
	isgomock struct{}
}

// MockPasswordProviderMockRecorder is the mock recorder for MockPasswordProvider.
type MockPasswordProviderMockRecorder struct {
	mock *MockPasswordProvider
}

// NewMockPasswordProvider creates a new mock instance.
func NewMockPasswordProvider(ctrl *gomock.Controller) *MockPasswordProvider {
	mock := &MockPasswordProvider{ctrl: ctrl}
	mock.recorder = &MockPasswordProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordProvider) EXPECT() *MockPasswordProviderMockRecorder {
	return m.recorder
}

// AlgorithmName mocks base method.
func (m *MockPasswordProvider) AlgorithmName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AlgorithmName")
	ret0, _ := ret[0].(string)
	return ret0
}

// AlgorithmName indicates an expected call of AlgorithmName.
func (mr *MockPasswordProviderMockRecorder) AlgorithmName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AlgorithmName", reflect.TypeOf((*MockPasswordProvider)(nil).AlgorithmName))
}

// ComparePasswordAndHash mocks base method.
func (m *MockPasswordProvider) ComparePasswordAndHash(password *securestring.SecureString, hash string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComparePasswordAndHash", password, hash)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ComparePasswordAndHash indicates an expected call of ComparePasswordAndHash.
func (mr *MockPasswordProviderMockRecorder) ComparePasswordAndHash(password, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComparePasswordAndHash", reflect.TypeOf((*MockPasswordProvider)(nil).ComparePasswordAndHash), password, hash)
}

// GenerateHashFromPassword mocks base method.
func (m *MockPasswordProvider) GenerateHashFromPassword(password *securestring.SecureString) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateHashFromPassword", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateHashFromPassword indicates an expected call of GenerateHashFromPassword.
func (mr *MockPasswordProviderMockRecorder) GenerateHashFromPassword(password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateHashFromPassword", reflect.TypeOf((*MockPasswordProvider)(nil).GenerateHashFromPassword), password)
}

// GenerateSecureRandomBytes mocks base method.
func (m *MockPasswordProvider) GenerateSecureRandomBytes(length int) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSecureRandomBytes", length)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateSecureRandomBytes indicates an expected call of GenerateSecureRandomBytes.
func (mr *MockPasswordProviderMockRecorder) GenerateSecureRandomBytes(length any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSecureRandomBytes", reflect.TypeOf((*MockPasswordProvider)(nil).GenerateSecureRandomBytes), length)
}

// GenerateSecureRandomString mocks base method.
func (m *MockPasswordProvider) GenerateSecureRandomString(length int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSecureRandomString", length)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateSecureRandomString indicates an expected call of GenerateSecureRandomString.
func (mr *MockPasswordProviderMockRecorder) GenerateSecureRandomString(length any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSecureRandomString", reflect.TypeOf((*MockPasswordProvider)(nil).GenerateSecureRandomString), length)
}
