// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/storage/database/cassandradb/cassandradb.go
//
// Generated by this command:
//
//	mockgen -source=pkg/storage/database/cassandradb/cassandradb.go -destination=pkg/mocks/mock_storage_database_cassandra_db.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
