// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/storage/memory/inmemory/memory.go
//
// Generated by this command:
//
//	mockgen -source=pkg/storage/memory/inmemory/memory.go -destination=pkg/mocks/mock_storage_memory_inmemory.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
