// web/maplefile-frontend/src/components/Register.jsx
// src/components/Register.jsx
import React, { useState, useEffect, useRef } from "react";
import { useNavigate, Link, useLocation } from "react-router";
import { useServices } from "../contexts/ServiceContext";
import CryptoService from "../services/CryptoService"; // Import CryptoService

const DiagnosticComponent = () => {
  useEffect(() => {
    const diagnoseLibSodium = async () => {
      console.log("=== LibSodium Diagnostic ===");

      try {
        // Test 1: Check if import worked
        const sodium = await import("libsodium-wrappers-sumo");
        console.log("✅ Import successful");
        console.log("Sodium object:", sodium);
        console.log("Sodium default:", sodium.default);

        const lib = sodium.default || sodium;

        // Test 2: Check if ready works
        console.log("Attempting sodium.ready...");
        await lib.ready;
        console.log("✅ Sodium.ready completed");

        // Test 3: Check available properties
        console.log("Available properties:", Object.keys(lib).slice(0, 10));
        console.log("Has randombytes_buf:", typeof lib.randombytes_buf);
        console.log("Has crypto_pwhash:", typeof lib.crypto_pwhash);

        // Test 4: Try basic operation
        const testBytes = lib.randombytes_buf(16);
        console.log(
          "✅ Basic operation works, generated bytes:",
          testBytes.length,
        );
      } catch (error) {
        console.error("❌ LibSodium diagnostic failed:");
        console.error("Error:", error);
        console.error("Error message:", error.message);
        console.error("Error stack:", error.stack);
      }
    };

    diagnoseLibSodium();
  }, []);

  return null;
};

const Register = () => {
  const { authService, cryptoService } = useServices(); // Inject cryptoService
  const navigate = useNavigate();
  const location = useLocation();
  const inputRef = useRef(null);

  // Form state
  const [name, setName] = useState("Bart Mika");
  const [email, setEmail] = useState("bart+1@mikasoftware.com");
  const [phone, setPhone] = useState("+1 (123) 456-7890");
  const [country, setCountry] = useState("Canada");
  const [password, setPassword] = useState("123password");
  const [confirmPassword, setConfirmPassword] = useState("123password");
  const [agreeTerms, setAgreeTerms] = useState(true);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const [betaAccessCode, setBetaAccessCode] = useState("BETA123");

  // Common countries list
  const countries = [
    "Canada",
    "United States",
    "United Kingdom",
    "Australia",
    "Germany",
    "France",
    "Italy",
    "Spain",
    "Netherlands",
    "Sweden",
    "Norway",
    "Denmark",
    "Other",
  ];

  // Handle form submission
  const handleSubmit = async (e) => {
    e.preventDefault();
    setError("");
    setLoading(true);

    try {
      console.log("Submitting...", {
        betaAccessCode,
        name,
        email,
        country,
        phone,
        password,
        confirmPassword,
        agreeTerms,
      });

      // Validate inputs
      if (
        !betaAccessCode ||
        !name ||
        !email ||
        !phone ||
        !password ||
        !confirmPassword
      ) {
        throw new Error("Please fill in all required fields");
      }

      if (!agreeTerms) {
        throw new Error("You must agree to the terms of service to continue");
      }

      // Check if passwords match
      if (password !== confirmPassword) {
        throw new Error("Passwords do not match");
      }

      // Check password length
      if (password.length < 8) {
        throw new Error("Password must be at least 8 characters long");
      }

      // Validate email format
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(email)) {
        throw new Error("Please enter a valid email address");
      }

      // Validate phone format (basic validation)
      const phoneRegex = /^[+]?[\d\s\-\(\)]{10,}$/;
      if (!phoneRegex.test(phone)) {
        throw new Error("Please enter a valid phone number");
      }

      // Ensure crypto service is ready
      console.log("handleSubmit - Ensuring CryptoService is ready...");
      await cryptoService.ensureReady(); // Wait for crypto service to initialize
      console.log("CryptoService is ready");

      // Generate registration crypto data
      console.log("handleSubmit - Generating registration crypto...");
      const cryptoData =
        await cryptoService.generateRegistrationCrypto(password);
      console.log("handleSubmit - Crypto data generated");

      // Attempt to register
      const result = await authService.register(
        email.trim(),
        name.trim(),
        phone.trim(),
        country,
        "America/Toronto",
        betaAccessCode.trim(),
        cryptoData.salt,
        cryptoData.publicKey,
        cryptoData.encryptedMasterKey,
        cryptoData.encryptedPrivateKey,
        cryptoData.encryptedRecoveryKey,
        cryptoData.masterKeyEncryptedWithRecoveryKey,
        cryptoData.verificationID,
      );

      if (result.success) {
        // Show recovery key info if provided
        if (result.recoveryKeyInfo) {
          alert(result.recoveryKeyInfo);
        }

        // Redirect to email verification page
        navigate("/verify-email", {
          state: {
            email: email.trim(),
            name: name.trim(),
          },
        });
      }
    } catch (err) {
      setError(err.message);
      console.error("Registration failed:", err); // Log the error
    } finally {
      setLoading(false);
    }
  };

  return (
    <div style={styles.container}>
      <div style={styles.formCard}>
        <h2 style={styles.title}>Create Your Account</h2>

        <DiagnosticComponent />

        {error && <div style={styles.error}>{error}</div>}

        <form onSubmit={handleSubmit} style={styles.form}>
          {/* ... (rest of your form fields) */}
          <div style={styles.formGroup}>
            <label htmlFor="name" style={styles.label}>
              Full Name *
            </label>
            <input
              type="text"
              id="name"
              value={name}
              onChange={(e) => setName(e.target.value)}
              style={styles.input}
              placeholder="Enter your full name"
              disabled={loading}
              required
            />
          </div>

          <div style={styles.formGroup}>
            <label htmlFor="email" style={styles.label}>
              Email Address *
            </label>
            <input
              type="email"
              id="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              style={styles.input}
              placeholder="Enter your email address"
              disabled={loading}
              required
            />
          </div>

          {/* ... (rest of your form fields) */}

          <div style={styles.formGroup}>
            <label htmlFor="password" style={styles.label}>
              Password *
            </label>
            <input
              type="password"
              id="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              style={styles.input}
              placeholder="Enter your password (min 8 characters)"
              disabled={loading}
              required
            />
          </div>

          <div style={styles.formGroup}>
            <label htmlFor="confirmPassword" style={styles.label}>
              Confirm Password *
            </label>
            <input
              type="password"
              id="confirmPassword"
              value={confirmPassword}
              onChange={(e) => setConfirmPassword(e.target.value)}
              style={styles.input}
              placeholder="Confirm your password"
              disabled={loading}
              required
            />
          </div>

          <div style={styles.checkboxGroup}>
            <label style={styles.checkboxLabel}>
              <input
                type="checkbox"
                checked={agreeTerms}
                onChange={(e) => setAgreeTerms(e.target.checked)}
                style={styles.checkbox}
                disabled={loading}
                required
              />
              <span style={styles.checkboxText}>
                I agree to the{" "}
                <a
                  href="#"
                  style={styles.link}
                  onClick={(e) => e.preventDefault()}
                >
                  Terms of Service
                </a>{" "}
                and{" "}
                <a
                  href="#"
                  style={styles.link}
                  onClick={(e) => e.preventDefault()}
                >
                  Privacy Policy
                </a>
              </span>
            </label>
          </div>

          <button
            type="submit"
            style={styles.button}
            disabled={loading || !agreeTerms}
          >
            {loading ? "Creating Account..." : "Create Account"}
          </button>
        </form>
        <p style={styles.switchText}>
          Already have an account?{" "}
          <Link to="/login" style={styles.link}>
            Login here
          </Link>
        </p>
      </div>
    </div>
  );
};

const styles = {
  container: {
    // Ensure the container takes up the full viewport height
    minHeight: "100vh",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f0f0f0",
  },
  formCard: {
    backgroundColor: "white",
    padding: "2rem",
    borderRadius: "8px",
    boxShadow: "0 2px 10px rgba(0, 0, 0, 0.1)",
    width: "100%",
    maxWidth: "500px",
  },
  title: {
    textAlign: "center",
    marginBottom: "1.5rem",
    color: "#333",
  },
  error: {
    backgroundColor: "#f8d7da",
    color: "#721c24",
    padding: "0.75rem",
    borderRadius: "4px",
    marginBottom: "1rem",
  },
  form: {
    display: "flex",
    flexDirection: "column",
  },
  formGroup: {
    marginBottom: "1rem",
  },
  label: {
    display: "block",
    marginBottom: "0.5rem",
    color: "#555",
    fontWeight: "bold",
  },
  input: {
    width: "100%",
    padding: "0.75rem",
    border: "1px solid #ddd",
    borderRadius: "4px",
    fontSize: "1rem",
    boxSizing: "border-box",
  },
  select: {
    width: "100%",
    padding: "0.75rem",
    border: "1px solid #ddd",
    borderRadius: "4px",
    fontSize: "1rem",
    boxSizing: "border-box",
    backgroundColor: "white",
  },
  hint: {
    display: "block",
    marginTop: "0.25rem",
    color: "#888",
    fontSize: "0.85rem",
  },
  checkboxGroup: {
    marginBottom: "1.5rem",
  },
  checkboxLabel: {
    display: "flex",
    alignItems: "flex-start",
    cursor: "pointer",
  },
  checkbox: {
    marginRight: "0.5rem",
    marginTop: "0.1rem",
  },
  checkboxText: {
    color: "#555",
    fontSize: "0.9rem",
    lineHeight: "1.4",
  },
  button: {
    backgroundColor: "#28a745",
    color: "white",
    padding: "0.75rem",
    border: "none",
    borderRadius: "4px",
    fontSize: "1rem",
    fontWeight: "bold",
    cursor: "pointer",
    marginBottom: "1rem",
  },
  switchText: {
    textAlign: "center",
    marginTop: "1rem",
    color: "#666",
  },
};

export default Register;
