// Code generated by MockGen. DO NOT EDIT.
// Source: internal/iam/usecase/federateduser/getbyemail.go
//
// Generated by this command:
//
//	mockgen -source=internal/iam/usecase/federateduser/getbyemail.go -destination=internal/iam/mocks/mock_usecase_federateduser_getbyemail.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	federateduser "github.com/mapleapps-ca/monorepo/cloud/mapleapps-backend/internal/iam/domain/federateduser"
	gomock "go.uber.org/mock/gomock"
)

// MockFederatedUserGetByEmailUseCase is a mock of FederatedUserGetByEmailUseCase interface.
type MockFederatedUserGetByEmailUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockFederatedUserGetByEmailUseCaseMockRecorder
	isgomock struct{}
}

// MockFederatedUserGetByEmailUseCaseMockRecorder is the mock recorder for MockFederatedUserGetByEmailUseCase.
type MockFederatedUserGetByEmailUseCaseMockRecorder struct {
	mock *MockFederatedUserGetByEmailUseCase
}

// NewMockFederatedUserGetByEmailUseCase creates a new mock instance.
func NewMockFederatedUserGetByEmailUseCase(ctrl *gomock.Controller) *MockFederatedUserGetByEmailUseCase {
	mock := &MockFederatedUserGetByEmailUseCase{ctrl: ctrl}
	mock.recorder = &MockFederatedUserGetByEmailUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFederatedUserGetByEmailUseCase) EXPECT() *MockFederatedUserGetByEmailUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockFederatedUserGetByEmailUseCase) Execute(ctx context.Context, email string) (*federateduser.FederatedUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, email)
	ret0, _ := ret[0].(*federateduser.FederatedUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockFederatedUserGetByEmailUseCaseMockRecorder) Execute(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockFederatedUserGetByEmailUseCase)(nil).Execute), ctx, email)
}
