// Code generated by MockGen. DO NOT EDIT.
// Source: internal/iam/usecase/emailer/sendpassreset.go
//
// Generated by this command:
//
//	mockgen -source=internal/iam/usecase/emailer/sendpassreset.go -destination=internal/iam/mocks/mock_usecase_sendpassreset.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	federateduser "github.com/mapleapps-ca/monorepo/cloud/mapleapps-backend/internal/iam/domain/federateduser"
	gomock "go.uber.org/mock/gomock"
)

// MockSendFederatedUserPasswordResetEmailUseCase is a mock of SendFederatedUserPasswordResetEmailUseCase interface.
type MockSendFederatedUserPasswordResetEmailUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockSendFederatedUserPasswordResetEmailUseCaseMockRecorder
	isgomock struct{}
}

// MockSendFederatedUserPasswordResetEmailUseCaseMockRecorder is the mock recorder for MockSendFederatedUserPasswordResetEmailUseCase.
type MockSendFederatedUserPasswordResetEmailUseCaseMockRecorder struct {
	mock *MockSendFederatedUserPasswordResetEmailUseCase
}

// NewMockSendFederatedUserPasswordResetEmailUseCase creates a new mock instance.
func NewMockSendFederatedUserPasswordResetEmailUseCase(ctrl *gomock.Controller) *MockSendFederatedUserPasswordResetEmailUseCase {
	mock := &MockSendFederatedUserPasswordResetEmailUseCase{ctrl: ctrl}
	mock.recorder = &MockSendFederatedUserPasswordResetEmailUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSendFederatedUserPasswordResetEmailUseCase) EXPECT() *MockSendFederatedUserPasswordResetEmailUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockSendFederatedUserPasswordResetEmailUseCase) Execute(ctx context.Context, monolithModule int, user *federateduser.FederatedUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, monolithModule, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockSendFederatedUserPasswordResetEmailUseCaseMockRecorder) Execute(ctx, monolithModule, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockSendFederatedUserPasswordResetEmailUseCase)(nil).Execute), ctx, monolithModule, user)
}
