// Code generated by MockGen. DO NOT EDIT.
// Source: internal/iam/usecase/federateduser/getbyid.go
//
// Generated by this command:
//
//	mockgen -source=internal/iam/usecase/federateduser/getbyid.go -destination=internal/iam/mocks/mock_usecase_federateduser_getbyid.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gocql "github.com/gocql/gocql"
	federateduser "github.com/mapleapps-ca/monorepo/cloud/mapleapps-backend/internal/iam/domain/federateduser"
	gomock "go.uber.org/mock/gomock"
)

// MockFederatedUserGetByIDUseCase is a mock of FederatedUserGetByIDUseCase interface.
type MockFederatedUserGetByIDUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockFederatedUserGetByIDUseCaseMockRecorder
	isgomock struct{}
}

// MockFederatedUserGetByIDUseCaseMockRecorder is the mock recorder for MockFederatedUserGetByIDUseCase.
type MockFederatedUserGetByIDUseCaseMockRecorder struct {
	mock *MockFederatedUserGetByIDUseCase
}

// NewMockFederatedUserGetByIDUseCase creates a new mock instance.
func NewMockFederatedUserGetByIDUseCase(ctrl *gomock.Controller) *MockFederatedUserGetByIDUseCase {
	mock := &MockFederatedUserGetByIDUseCase{ctrl: ctrl}
	mock.recorder = &MockFederatedUserGetByIDUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFederatedUserGetByIDUseCase) EXPECT() *MockFederatedUserGetByIDUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockFederatedUserGetByIDUseCase) Execute(ctx context.Context, id gocql.UUID) (*federateduser.FederatedUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, id)
	ret0, _ := ret[0].(*federateduser.FederatedUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockFederatedUserGetByIDUseCaseMockRecorder) Execute(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockFederatedUserGetByIDUseCase)(nil).Execute), ctx, id)
}
