// Code generated by MockGen. DO NOT EDIT.
// Source: internal/iam/domain/federateduser/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/iam/domain/federateduser/interface.go -destination=internal/iam/mocks/mock_repository_federateduser.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gocql "github.com/gocql/gocql"
	federateduser "github.com/mapleapps-ca/monorepo/cloud/mapleapps-backend/internal/iam/domain/federateduser"
	gomock "go.uber.org/mock/gomock"
)

// MockFederatedUserRepository is a mock of FederatedUserRepository interface.
type MockFederatedUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFederatedUserRepositoryMockRecorder
	isgomock struct{}
}

// MockFederatedUserRepositoryMockRecorder is the mock recorder for MockFederatedUserRepository.
type MockFederatedUserRepositoryMockRecorder struct {
	mock *MockFederatedUserRepository
}

// NewMockFederatedUserRepository creates a new mock instance.
func NewMockFederatedUserRepository(ctrl *gomock.Controller) *MockFederatedUserRepository {
	mock := &MockFederatedUserRepository{ctrl: ctrl}
	mock.recorder = &MockFederatedUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFederatedUserRepository) EXPECT() *MockFederatedUserRepositoryMockRecorder {
	return m.recorder
}

// CheckIfExistsByEmail mocks base method.
func (m *MockFederatedUserRepository) CheckIfExistsByEmail(ctx context.Context, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIfExistsByEmail", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckIfExistsByEmail indicates an expected call of CheckIfExistsByEmail.
func (mr *MockFederatedUserRepositoryMockRecorder) CheckIfExistsByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIfExistsByEmail", reflect.TypeOf((*MockFederatedUserRepository)(nil).CheckIfExistsByEmail), ctx, email)
}

// Create mocks base method.
func (m_2 *MockFederatedUserRepository) Create(ctx context.Context, m *federateduser.FederatedUser) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFederatedUserRepositoryMockRecorder) Create(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFederatedUserRepository)(nil).Create), ctx, m)
}

// DeleteByEmail mocks base method.
func (m *MockFederatedUserRepository) DeleteByEmail(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByEmail", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByEmail indicates an expected call of DeleteByEmail.
func (mr *MockFederatedUserRepositoryMockRecorder) DeleteByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByEmail", reflect.TypeOf((*MockFederatedUserRepository)(nil).DeleteByEmail), ctx, email)
}

// DeleteByID mocks base method.
func (m *MockFederatedUserRepository) DeleteByID(ctx context.Context, id gocql.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockFederatedUserRepositoryMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockFederatedUserRepository)(nil).DeleteByID), ctx, id)
}

// GetByEmail mocks base method.
func (m *MockFederatedUserRepository) GetByEmail(ctx context.Context, email string) (*federateduser.FederatedUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*federateduser.FederatedUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockFederatedUserRepositoryMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockFederatedUserRepository)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockFederatedUserRepository) GetByID(ctx context.Context, id gocql.UUID) (*federateduser.FederatedUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*federateduser.FederatedUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockFederatedUserRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockFederatedUserRepository)(nil).GetByID), ctx, id)
}

// GetByVerificationCode mocks base method.
func (m *MockFederatedUserRepository) GetByVerificationCode(ctx context.Context, verificationCode string) (*federateduser.FederatedUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByVerificationCode", ctx, verificationCode)
	ret0, _ := ret[0].(*federateduser.FederatedUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByVerificationCode indicates an expected call of GetByVerificationCode.
func (mr *MockFederatedUserRepositoryMockRecorder) GetByVerificationCode(ctx, verificationCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByVerificationCode", reflect.TypeOf((*MockFederatedUserRepository)(nil).GetByVerificationCode), ctx, verificationCode)
}

// UpdateByID mocks base method.
func (m_2 *MockFederatedUserRepository) UpdateByID(ctx context.Context, m *federateduser.FederatedUser) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "UpdateByID", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockFederatedUserRepositoryMockRecorder) UpdateByID(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockFederatedUserRepository)(nil).UpdateByID), ctx, m)
}
