// Code generated by MockGen. DO NOT EDIT.
// Source: internal/iam/usecase/federateduser/getbyverify.go
//
// Generated by this command:
//
//	mockgen -source=internal/iam/usecase/federateduser/getbyverify.go -destination=internal/iam/mocks/mock_usecase_federateduser_getbyverify.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	federateduser "github.com/mapleapps-ca/monorepo/cloud/mapleapps-backend/internal/iam/domain/federateduser"
	gomock "go.uber.org/mock/gomock"
)

// MockFederatedUserGetByVerificationCodeUseCase is a mock of FederatedUserGetByVerificationCodeUseCase interface.
type MockFederatedUserGetByVerificationCodeUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockFederatedUserGetByVerificationCodeUseCaseMockRecorder
	isgomock struct{}
}

// MockFederatedUserGetByVerificationCodeUseCaseMockRecorder is the mock recorder for MockFederatedUserGetByVerificationCodeUseCase.
type MockFederatedUserGetByVerificationCodeUseCaseMockRecorder struct {
	mock *MockFederatedUserGetByVerificationCodeUseCase
}

// NewMockFederatedUserGetByVerificationCodeUseCase creates a new mock instance.
func NewMockFederatedUserGetByVerificationCodeUseCase(ctrl *gomock.Controller) *MockFederatedUserGetByVerificationCodeUseCase {
	mock := &MockFederatedUserGetByVerificationCodeUseCase{ctrl: ctrl}
	mock.recorder = &MockFederatedUserGetByVerificationCodeUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFederatedUserGetByVerificationCodeUseCase) EXPECT() *MockFederatedUserGetByVerificationCodeUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockFederatedUserGetByVerificationCodeUseCase) Execute(ctx context.Context, verificationCode string) (*federateduser.FederatedUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, verificationCode)
	ret0, _ := ret[0].(*federateduser.FederatedUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockFederatedUserGetByVerificationCodeUseCaseMockRecorder) Execute(ctx, verificationCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockFederatedUserGetByVerificationCodeUseCase)(nil).Execute), ctx, verificationCode)
}
